apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "argocd-helm-server.fullname" . }}
  labels:
    {{- include "argocd-helm-server.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: "{{ .Values.externalSecretsStoreName }}"
    kind: "{{ .Values.externalSecretsStoreKind }}"
  target:
    name: "{{ .Values.externalSecretCreatedSecretName }}"
  data:
  - secretKey: "{{ .Values.externalSecretCreatedSecretKeyName }}"
    remoteRef:
      key: "{{ .Values.externalSecretRefSecretKeyName }}"
      version: v1
